Update ses Package Version to 1.3.0
Agoric/dapp-offer-up pull request #66
Opened 2024-02-26 07:58 UTC by rabi-siddique

The Offer-Up DAPP had loading issues on the latest versions of Brave and Chrome. To address this, I upgraded the ses package to version 1.3.0, resolving the compatibility issue.

2024-02-26 09:40 UTC, samsiegart requested changes
Thanks Rabi! Mind also updating the version in `ui/package.json`?

2024-02-26 14:45 UTC, rabi-siddique commented
> Thanks Rabi! Mind also updating the version in `ui/package.json`?

Thanks for pointing it out, Sam. Done!

2024-02-26 15:52 UTC, otoole-brendan commented
Created https://github.com/Agoric/dapp-offer-up/pull/66 as the issue to track this PR

2024-02-27 11:00 UTC, samsiegart commented
@rabi-siddique Looks like `cd ui && yarn build` is failing due to an unused `@ts-expect-error` (I guess with the new ses version the exception is unneeded). I tried removing this line and it built locally: https://github.com/rabi-siddique/rs-dapp-offer-up/blob/3fddc34be347b55747c96a094448f022b03454ab/ui/src/installSesLockdown.ts#L6

Would you be able to remove that line in your fork? Then we can push this. Thanks!

2024-02-27 11:25 UTC, rabi-siddique commented
@samsiegart Done. Thanks for inspecting. I've removed the line and the build works properly on local.

2024-02-27 11:38 UTC, samsiegart approved these changes
LGTM

2024-02-27 11:38 UTC, merged